### ISSUE TITLE
Task definition

### ISSUE THREAD

**Issue by VJftw** [velocity-ci/velocity#2]
## User defines a task

Users define tasks in yaml/yml files in `./vtasks/`.

* Parameters can be defined and reused with `${}`

Example tasks:
```
description: "Shows environment"
name: env
parameters: 
  - default: testing
    name: e
steps: 
  - type: run
    image: library/alpine
    command: 
      - env
    description: "Show environment"
    environment: 
      WOO: "${e}"
      ${e}: AAAA
```
