### ISSUE TITLE
Build plan

### ISSUE THREAD

**Issue by VJftw** [velocity-ci/velocity#4]
Build plans will be ran on every push with commits or can be ran locally.

In project root, `.velocity` can contain
```
plan:
 - name: test
   tasks:
      - vtasks/test_web
      - vtasks/test_api
- name: deploy
  tasks:
     - vtasks/deploy
```

Tasks in the same group will be parallelised, e.g. In the above example, `vtasks/test_web` and `vtasks/test_api` will be parallelised but `deploy` will run after `test` if successful.
